apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: core-platform-proxy
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 3
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              nodeTaintsPolicy: Honor
              labelSelector:
                matchLabels:
                  gateway.envoyproxy.io/owning-gateway-name: core-platform
                  gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system
              # Balance each rollout independently from the retiring pods.
              matchLabelKeys:
                - pod-template-hash
        container:
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
      envoyService:
        externalTrafficPolicy: Cluster
        patch:
          type: StrategicMerge
          value:
            spec:
              ports:
                - name: https-443
                  port: 443
                  appProtocol: k8s.timeweb.cloud/proto-tcp
                - name: http-80
                  port: 80
                  appProtocol: k8s.timeweb.cloud/proto-tcp
