apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-gateway-config
  namespace: envoy-gateway-system
  labels:
    app.kubernetes.io/instance: eg
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gateway-helm
    app.kubernetes.io/version: v1.8.0
    helm.sh/chart: gateway-helm-v1.8.0
  annotations:
    meta.helm.sh/release-name: eg
    meta.helm.sh/release-namespace: envoy-gateway-system
data:
  envoy-gateway.yaml: |-
    apiVersion: gateway.envoyproxy.io/v1alpha1
    kind: EnvoyGateway
    extensionApis:
      enableEnvoyPatchPolicy: true
    gateway:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
    logging:
      level:
        default: info
    provider:
      kubernetes:
        leaderElection:
          disable: true
        rateLimitDeployment:
          container:
            image: docker.io/envoyproxy/ratelimit:ff287602
          patch:
            type: StrategicMerge
            value:
              spec:
                template:
                  spec:
                    containers:
                      - imagePullPolicy: IfNotPresent
                        name: envoy-ratelimit
        shutdownManager:
          image: docker.io/envoyproxy/gateway:v1.8.0
      type: Kubernetes
