apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: core-platform-proxy
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        externalTrafficPolicy: Cluster
        patch:
          type: StrategicMerge
          value:
            spec:
              ports:
                - name: https-443
                  port: 443
                  appProtocol: k8s.timeweb.cloud/proto-tcp
                - name: http-80
                  port: 80
                  appProtocol: k8s.timeweb.cloud/proto-tcp
