apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: core-platform-proxy
    namespace: envoy-gateway-system
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: core-platform
  namespace: envoy-gateway-system
spec:
  gatewayClassName: envoy
  listeners:
    - name: argocd-https
      protocol: HTTPS
      port: 443
      hostname: "argocd.panixida.ru"
      tls:
        mode: Terminate
        certificateRefs:
          - name: argocd-panixida-ru-tls
      allowedRoutes:
        namespaces:
          from: All
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.panixida.ru"
      allowedRoutes:
        namespaces:
          from: All
    - name: headlamp-https
      protocol: HTTPS
      port: 443
      hostname: "headlamp.panixida.ru"
      tls:
        mode: Terminate
        certificateRefs:
          - name: headlamp-panixida-ru-tls
      allowedRoutes:
        namespaces:
          from: All
