---
all:
  children:
    core_platform:
      hosts:
        production:
          ansible_host: "{{ lookup('env', 'SERVER_HOST') | default('127.0.0.1', true) }}"
          ansible_user: "{{ lookup('env', 'SERVER_USER') | default('root', true) }}"
          ansible_python_interpreter: /usr/bin/python3
