apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - applications/platform-workloads.yaml
  - platform/namespaces.yaml
  - platform/envoyproxy.yaml
  - platform/gateway.yaml
  - platform/certificates.yaml
  - platform/internal-gateway-service.yaml
  - platform/coredns-internal-platform.yaml
  - platform/oidc-rbac.yaml
  - platform/routes.yaml
