apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - applications/kargo.yaml
  - applications/platform-workloads.yaml
  - applications/dotnet-template.yaml
  - applications/dotnet-template-kargo.yaml
  - platform/namespaces.yaml
  - platform/coredns.yaml
  - platform/envoy-gateway-config.yaml
  - platform/envoyproxy.yaml
  - platform/gateway.yaml
  - platform/grafana-alerting-redirect.yaml
  - platform/certificates.yaml
  - platform/oidc-rbac.yaml
  - platform/routes.yaml
